stages: - test 
laravel_test: 
stage: test 
image: php:8.2 
before_script: - apt-get update && apt-get install -y unzip git - curl -sS https://getcomposer.org/installer | php - php composer.phar install - cp .env.example .env - php artisan key:generate 
script: - php artisan test